[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeophysicalModelGenerator = "3700c31b-fa53-48a6-808a-ef22d5a84742"

[compat]
Documenter = "1"
